/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example API is running */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthCredentials"];
                };
            };
            responses: {
                /** @description User registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive a JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthCredentials"];
                };
            };
            responses: {
                /** @description Login succeeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a user without returning a token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthCredentials"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own user by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Update own user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description Updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete own user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own pets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a pet for the authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePetRequest"];
                };
            };
            responses: {
                /** @description Created pet */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get own pet by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Update own pet */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePetRequest"];
                };
            };
            responses: {
                /** @description Updated pet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete own pet */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 1 */
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted pet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/veterinary-clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search nearby veterinary clinics
         * @description Returns clinics from Google Places and local CSV data in one paginated response. Duplicate clinics are merged.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description User latitude. Alias: lat.
                     * @example 48.8566
                     */
                    latitude?: number;
                    /**
                     * @description User longitude. Alias: lng.
                     * @example 2.3522
                     */
                    longitude?: number;
                    /** @example 48.8566 */
                    lat?: number;
                    /** @example 2.3522 */
                    lng?: number;
                    /**
                     * @description Search distance in kilometers.
                     * @example 5
                     */
                    distance?: 5 | 10 | 25 | 50;
                    /** @example true */
                    openNow?: boolean;
                    /** @example false */
                    open24_7?: boolean;
                    /** @description Comma-separated services. Repeated service parameters are also accepted. */
                    services?: string;
                    /** @example true */
                    emergency?: boolean;
                    sort?: "nearest" | "rating";
                    page?: number;
                    pageSize?: number;
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nearby clinics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VeterinaryClinicListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Google Places error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/veterinary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias for /veterinary-clinics */
        get: {
            parameters: {
                query?: {
                    /** @example 48.8566 */
                    lat?: number;
                    /** @example 2.3522 */
                    lng?: number;
                    /** @example 5 */
                    distance?: 5 | 10 | 25 | 50;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nearby clinics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VeterinaryClinicListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example Invalid query parameters */
            message: string;
            details?: {
                /** @example latitude */
                field?: string;
                /** @example latitude must be a number */
                message?: string;
            }[];
        };
        AuthCredentials: {
            /** @example anton */
            username: string;
            /** @example secret123 */
            password: string;
        };
        User: {
            /** @example 1 */
            id: number;
            /** @example anton */
            username: string;
            pets?: components["schemas"]["Pet"][];
        };
        AuthResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token: string;
            user: components["schemas"]["User"];
        };
        CreatePetRequest: {
            /** @example Barsik */
            name: string;
            /** @example cat */
            type: string;
        };
        UpdatePetRequest: {
            /** @example Marsik */
            name?: string;
            /** @example dog */
            type?: string;
        };
        Pet: {
            /** @example 1 */
            id: number;
            /** @example Barsik */
            name: string;
            /** @example cat */
            type: string;
            /** @example 1 */
            userId: number;
        };
        UpdateUserRequest: {
            /** @example anton_new */
            username?: string;
            /** @example new-secret123 */
            password?: string;
        };
        ClinicIcon: {
            /** @example https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png */
            url: string | null;
            /** @example #7B9EB0 */
            backgroundColor: string | null;
            /** @example https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet */
            maskBaseUri: string | null;
        };
        ClinicLocation: {
            /** @example 48.8566 */
            lat: number;
            /** @example 2.3522 */
            lng: number;
        };
        VeterinaryClinic: {
            /** @example ChIJ_VVBcBtu5kcRex3O07t5U0s */
            id: string;
            /** @example Clinique Veterinaire */
            name: string | null;
            /** @example true */
            isOperational: boolean;
            /** @example true */
            isOpenNow: boolean | null;
            /** @example false */
            isOpen24_7: boolean | null;
            /** @example 4.5 */
            rating: number | null;
            /** @example 114 */
            userRatingsTotal: number | null;
            /** @example +33 1 42 74 81 13 */
            phone: string | null;
            /** @example 26 Rue Beaubourg, 75003 Paris, France */
            address: string | null;
            /** @example https://example.com */
            website: string | null;
            /** @example https://maps.google.com/?cid=5427815823530925435 */
            googleMapsUrl: string | null;
            location: components["schemas"]["ClinicLocation"] | null;
            /** @example 1303 */
            distanceMeters: number | null;
            icon: components["schemas"]["ClinicIcon"];
            /**
             * @example [
             *       "consultation",
             *       "vaccination",
             *       "emergency"
             *     ]
             */
            services: string[];
            /** @example true */
            isEmergency: boolean;
            /**
             * @example [
             *       "veterinary_care",
             *       "health"
             *     ]
             */
            types: string[];
            /**
             * @example [
             *       "google",
             *       "csv"
             *     ]
             */
            sources: ("google" | "csv")[];
        };
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 10 */
            pageSize: number;
            /** @example 25 */
            total: number;
            /** @example 3 */
            totalPages: number;
            /** @example true */
            hasNextPage: boolean;
            /** @example false */
            hasPreviousPage: boolean;
        };
        VeterinaryClinicListResponse: {
            clinics: components["schemas"]["VeterinaryClinic"][];
            pagination: components["schemas"]["Pagination"];
            filters: {
                /**
                 * @example 5
                 * @enum {integer}
                 */
                distanceKm?: 5 | 10 | 25 | 50;
                /** @example true */
                openNow?: boolean | null;
                /** @example null */
                open24_7?: boolean | null;
                /**
                 * @example [
                 *       "consultation"
                 *     ]
                 */
                services?: string[];
                /** @example false */
                emergency?: boolean | null;
                /**
                 * @example nearest
                 * @enum {string}
                 */
                sort?: "nearest" | "rating";
            };
            sources: {
                /** @example 20 */
                google: number;
                /** @example 5 */
                csv: number;
                /** @example 25 */
                merged: number;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example 1 */
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
